### ISSUE TITLE
MKTXP Launch error with DHCP leases parameter

### ISSUE THREAD

**Issue by DemianBerg** [M0r13n/mikrotik_monitoring#10]
When I run MKTXP with the DHCP Leases parameter, it gives an error, when I change it from True to False, everything starts successfully 🤔

![image](https://user-images.githubusercontent.com/46506741/192344313-864c99da-a4ab-4738-88ef-44aba380691b.png)

**Comment by M0r13n** [comment]
I was able to reproduce this issue. But the bug lives in the exporter itself (mktxp). I created a PR in the project. 

Refer to: https://github.com/akpw/mktxp/pull/39
