### ISSUE TITLE
Adding additional Nodes

### ISSUE THREAD

**Issue by JaZzSuperman** [M0r13n/mikrotik_monitoring#16]
Hi

I am trying to add a additional 3 routers to the config file.

Do I just add the additional router addresses below the IP address field.

Or do I need to copy the entire config and paste that below the original one with the different IP address of the other router?

I have currently tried both and no data is showing when i do so?

**Comment by M0r13n** [comment]
Hey,

you need to add each device under a dedicated section:

```txt
[Sample-Router-1]
    enabled = True
    hostname = localhost 
    port = 8728

[Sample-Router-2]
    enabled = True
    hostname = localhost 
    port = 8728 
```

**Comment by JaZzSuperman** [comment]
Thanks for your reply

I have added in the additional router below and left the password section
the same as for testing I will use the same API group and username.

Do I need to reboot one of the containers in order for the additional to
show up?

Only reason I ask is because on the node drop down menu I do not see the
second address entry?

Kind Regards
Jarryd

**Comment by M0r13n** [comment]
Yep. Just restart the whole stack with `docker-compose restart`

**Comment by JaZzSuperman** [comment]
Thanks Leon

Much appreciated , I will give that a try

**Comment by M0r13n** [comment]
I consider this issue to be closed.
