### ISSUE TITLE
Option to disable speedtest

### ISSUE THREAD

**Issue by dilocker** [M0r13n/mikrotik_monitoring#17]
I noticed every 7 minutes that a good amount of traffic was outbound to 184.182.243.193:8080 coming from the monitoring container. Upon resolving, this was to an Ookla server (no idea if this is hosted by Ookla themselves, but returns a Cox owned IP), so I'm guessing this is the speedtest to show bandwidth in the grafana dashboard. Would be nice to be able to turn this off as it may impact online gaming and really not useful info (have no idea the geographic location of this address). For now I can just block this address outbound, though.

**Comment by M0r13n** [comment]
Hey @dilocker,

you just need to set `bandwidth = False` [in the mktxp/_mktxp.conf file](https://github.com/M0r13n/mikrotik_monitoring/blob/38600b8cbcabbbf1dc96ea30446c30b905a463c7/mktxp/_mktxp.conf#L22)

**Comment by M0r13n** [comment]
If you encounter any problem, feel free to reopen the issue.

Best whishes
Leon

**Comment by dilocker** [comment]
AH, didn't even see that .conf file before, only the mktxp.conf. Thanks!
