### ISSUE TITLE
support on mikrotil router os 6.x.x ?

### ISSUE THREAD

**Issue by Firsaavln** [M0r13n/mikrotik_monitoring#20]
anyone, Does this project support router OS 6.x.x and also run on Linux Debian VMware?

**Comment by M0r13n** [comment]
@Firsaavln The Prometheus exporter mktxp supports both version 6 and 7 of RouterOS. And because this project is based on Docker, it runs on most operating systems including (virtualized) Debian. You just need to make sure, that Docker and Docker-Compose are available on the target system.
