### ISSUE TITLE
[QUESTION] Host Config

### ISSUE THREAD

**Issue by antwal** [M0r13n/mikrotik_monitoring#24]
Which instance does this host refer to? 

https://github.com/M0r13n/mikrotik_monitoring/blob/7fb2f026349f4622c6f1e49c3be225af3f090853/prometheus/prometheus.yml#L32

I don't use your docker configuration, but I need to create a stack dedicated to my need

**Comment by M0r13n** [comment]
Hey @antwal,

actually, I am not really sure if this line does anything at all (anymore). It might very well be the case that this line is an obsolete artifact

**Comment by antwal** [comment]
ok fine, I'm adjusting the configuration as I also use prometheus for home assistant and ubiquiti
