### ISSUE TITLE
No Issue - just thank you.. 

### ISSUE THREAD

**Issue by bcookatpcsd** [M0r13n/mikrotik_monitoring#25]
![image](https://github.com/M0r13n/mikrotik_monitoring/assets/55087301/4fa228ff-f35d-43c5-99b8-31fab5d943fb)

![image](https://github.com/M0r13n/mikrotik_monitoring/assets/55087301/e535e516-1cde-434e-a2a3-496c0e24eada)
Amazon Eero 6+ in bridge mode attached to a hEX (eero in bridge mode is amazing, yes still does mesh..)

fq_codel in queue tree with *no bw* limits; queue tree uses fasttrack simple queue does not.. (must be entered via cli)

https://www.animmouse.com/p/fix-bufferbloat-on-mikrotik-without-disabling-fasttrack/

Anyway, thank you.. 

Donation link?

**Comment by M0r13n** [comment]
@bcookatpcsd Thank you! 😊 I am glad that you find this project useful. 

> Donation link?

That’s kind of you, but there is no need for this. This software is free for everyone to use.
