### ISSUE TITLE
mikrotik_exporter:9436

### ISSUE THREAD

**Issue by bcookatpcsd** [M0r13n/mikrotik_monitoring#26]
[prometheus/prometheus.yml](https://github.com/M0r13n/mikrotik_monitoring/blob/7fb2f026349f4622c6f1e49c3be225af3f090853/prometheus/prometheus.yml#L32)

I see this host being asked for in DNS, but I don't see anything listening in any of the containers.. should it be? 

but I do see 49090

```
docker exec -it mikrotik-mktxp netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 127.0.0.11:42195        0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:49090           0.0.0.0:*               LISTEN      
tcp        0      0 172.18.0.3:49090        172.18.0.5:43912        TIME_WAIT   
tcp        0      0 172.18.0.3:52014        192.168.88.1:8728       ESTABLISHED 
tcp        0      0 172.18.0.3:49090        172.18.0.5:35862        TIME_WAIT   
tcp        0      0 172.18.0.3:49090        172.18.0.5:37194        TIME_WAIT   
tcp        0      0 172.18.0.3:49090        172.18.0.5:58176        TIME_WAIT   
udp        0      0 127.0.0.11:51610        0.0.0.0:*                           
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path
```

(hope this makes sense..)

Thank you in advance.

**Comment by M0r13n** [comment]
@bcookatpcsd You are right. This line is a leftover without any effect. This was already pointed out by another user [recently](https://github.com/M0r13n/mikrotik_monitoring/issues/24#issuecomment-1873302164). But I forgot to remove the line

**Comment by M0r13n** [comment]
Remove the line in the latest PR
