### ISSUE TITLE
Internet Latency and Internet Bandwidth graphs question

### ISSUE THREAD

**Issue by 80kk** [M0r13n/mikrotik_monitoring#3]
Hi,
I've got it running, thanks. However I can't find anything about Internet Latency settings. It is taking measures from something but I can't figure it what IP it is being used and if it is possible to change it?

Very similar question regarding the Internet Bandwidth graph it looks like it is constantly measure it but I can't see this in my Mikrotik traffic. How this works?

**Comment by M0r13n** [comment]
Hi @80kk 👋,

this functionality is provided by mktxp, the Prometheus exporter. This Python module integrates the free [speedtest.net API](https://github.com/akpw/mktxp/blob/4962efd2a717742049d607a95303fbedb298d7bd/mktxp/collector/bandwidth_collector.py#L61), which is configured to run regularly by default. This can be configured:

```txt
bandwidth = True                # Turns metrics bandwidth metrics collection on / off    
bandwidth_test_interval = 420   # Interval for colllecting bandwidth metrics
```
