### ISSUE TITLE
some principal question about this project

### ISSUE THREAD

**Issue by PackElend** [M0r13n/mikrotik_monitoring#6]
Hi Leon,
I am currently browsing the internet for a good visualisation to monitor my MTs (10x units) and came across your site (among others).
May I ask a few questions about why you started your own project as there is a similar project and so on?

1. have you considered using: https://github.com/IgorKha/Grafana-Mikrotik? 
(I know that https://grafana.com/grafana/dashboards/?search=mikrotik does not show that much useful)
2. for what purpose do you use the REST API as it would require opening the Firewall if the Raspi is not in the same VLAN as the MTs (my case)
3. why you don't use the official SNMP exporter https://github.com/prometheus/snmp_exporter?
4. Have you ever used [The Dude](https://mikrotik.com/thedude) as I start with as that is familiar for the MT vendors? 
Going your way is the cherry on the cream  :). 
5. Have you tried to implement the syslog as well, see https://grafana.com/blog/2021/03/23/how-i-fell-in-love-with-logs-thanks-to-grafana-loki?
6. (going via Zabbix, I cannot find the website anymore but https://twitter.com/alexanderzobnin/status/841631679064227840?lang=en and https://github.com/alexanderzobnin/grafana-zabbix)

thank you 
stefan

**Comment by M0r13n** [comment]
Hi @PackElend,

> have you considered using: https://github.com/IgorKha/Grafana-Mikrotik?

At the time that I started to work on this, the mentioned  project did not yet exist. If you take a look at the commit history, you will see, that both projects started roughly at the same point in time.

> for what purpose do you use the REST API as it would require opening the Firewall if the Raspi is not in the same VLAN as the MTs (my case)

Don't you need to also expose the device through the firewall when using SNMP?

The nice thing about the API is its flexibility. You can basically get every metric possible.

> why you don't use the official SNMP exporter

Firstly it's painfully slow. In my experience SNMP walks are very slow and CPU heavy. [And I am not alone with this](https://forum.mikrotik.com/viewtopic.php?t=132304). In my experience the API is much faster and produces less stress on the CPU of the monitored device.

Secondly I never really got used to the way that SNMP metrics and queries are structured. I find them very hard to read. 

> Have you ever used [The Dude](https://mikrotik.com/thedude) as I start with as that is familiar for the MT vendors?

Nope. I never used The Dude.

> Have you tried to implement the syslog as well

Nope.

I hope that this answers your questions. Feel free to ask if there is anything unclear. :-)

**Comment by PackElend** [comment]
> At the time that I started to work on this, the mentioned project did not yet exist. If you take a look at the commit history, you will see, that both projects started roughly at the same point in time.

I checked that before I wrote the project a few months apart but it is really little. Just curious if you check that and decided against it.

By the way, do you follow your "competitor"? 

> The` nice thing about the API is its flexibility. You can basically get every metric possible.

I'm not aware of the refresh rate on the SNMP nor API, is it reasonable quick? 

> I hope that this answers your questions. Feel free to ask if there is anything unclear. :-)

a lot :) may you want to pick some questions and create an FAQ as there might be others asking the same question again?


I hope that I can still hop on this year  🤞

**Comment by M0r13n** [comment]
> By the way, do you follow your "competitor"?

This project is only a personal hobby. It do it mainly to learn something and to improve my skills. Therefore, I don't really need to compete with anyone.

 > I'm not aware of the refresh rate on the SNMP nor API, is it reasonable quick?

I never really used SNMP based monitoring for Mikrotik devices. So I can not really tell anything about the performance. The API is fast enough for me. A full scrape takes less than a second. 

> I hope that I can still hop on this year

Good luck and have fun!  :four_leaf_clover:
